// <auto-generated />
using System;
using GesCPSI_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GesCPSI_Project.Migrations
{
    [DbContext(typeof(GesDbContext))]
    [Migration("20260609084745_AddActeWorkflowFields")]
    partial class AddActeWorkflowFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GesCPSI_Project.Models.AjoutActModel", b =>
                {
                    b.Property<int>("IdAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAjout"));

                    b.Property<string>("CategorieClient")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LibelleAct")
                        .HasColumnType("text");

                    b.Property<string>("NomAct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.HasKey("IdAjout");

                    b.ToTable("AjoutActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.AuditLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int?>("StatutApres")
                        .HasColumnType("integer");

                    b.Property<int?>("StatutAvant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdActe");

                    b.HasIndex("IdUser");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.AutorisationModel", b =>
                {
                    b.Property<int>("IdAutorisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAutorisation"));

                    b.Property<string>("ConditionsAutorisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAutorisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<string>("LieuAutorisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantMaxAutorise")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroAutorisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAutorisation");

                    b.HasIndex("IdActe")
                        .IsUnique();

                    b.ToTable("AutorisationModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.BanqueModel", b =>
                {
                    b.Property<int>("IdBnq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBnq"));

                    b.Property<string>("CapitalSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailBnq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FonctionRepresentant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormeJuridique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomCollaborateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomRaisonSocialBnq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistreCommerce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepresentantBnq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiegeSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SigleBnq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Swift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelBnq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisaCollaborateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBnq");

                    b.ToTable("BanqueModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.CautionnementModel", b =>
                {
                    b.Property<int>("IdCautionnement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCautionnement"));

                    b.Property<string>("ClauseNonNovation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClauseSubrogation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionsRevocationCautionmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEffetCautionmt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpirationCautionmt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSignatureCautionmt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElectionDomicile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EtatCautionmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<string>("LieuSignatureCautionmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantCautionne")
                        .HasColumnType("numeric");

                    b.Property<string>("MontantLettreCautionmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomTypesActe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCautionmt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObligationsBanque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObligationsCaution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReglementDifferend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCautionnement");

                    b.HasIndex("IdActe")
                        .IsUnique();

                    b.ToTable("CautionnementModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ChargeModel", b =>
                {
                    b.Property<int>("IdCharge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCharge"));

                    b.Property<DateTime>("DateCharge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantCharge")
                        .HasColumnType("numeric");

                    b.Property<string>("PayePar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatutCharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeCharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCharge");

                    b.HasIndex("IdActe")
                        .IsUnique();

                    b.ToTable("ChargeModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ClientActModel", b =>
                {
                    b.Property<int>("IdCltActe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCltActe"));

                    b.Property<string>("DescriptionRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<int>("IdClt")
                        .HasColumnType("integer");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.HasKey("IdCltActe");

                    b.HasIndex("IdActe");

                    b.HasIndex("IdClt");

                    b.HasIndex("IdRole");

                    b.ToTable("ClientActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ClientModel", b =>
                {
                    b.Property<int>("IdClt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClt"));

                    b.Property<string>("Adressecomplet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BPClt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("text");

                    b.Property<bool>("CopiePieceJointe")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateDelivPiece")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateMariage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateNaiss")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePVDelib")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FonctionRepresentant")
                        .HasColumnType("text");

                    b.Property<string>("FormeJuridique")
                        .HasColumnType("text");

                    b.Property<string>("LieuDelivPiece")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LieuMariage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LieuNaiss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomConjoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomRaisonsociale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomRepresentant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumIdentifFiscal")
                        .HasColumnType("text");

                    b.Property<string>("NumPieceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumRCCM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaysNaiss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaysResidn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonDelivPiece")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionClt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefPVDelib")
                        .HasColumnType("text");

                    b.Property<string>("RegimeMatrim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistreCommerce")
                        .HasColumnType("text");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiegeSocial")
                        .HasColumnType("text");

                    b.Property<string>("SituationMatrim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelBur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelCel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelDom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypePieceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VilleCommune")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdClt");

                    b.HasIndex("NomRaisonsociale");

                    b.ToTable("ClientModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.EntiteJurModel", b =>
                {
                    b.Property<int>("IdEntiteJur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntiteJur"));

                    b.Property<DateTime>("DateActeJuridique")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FonctionResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<string>("NomDossier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomHuissier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDossier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VilleHuissier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEntiteJur");

                    b.HasIndex("IdActe")
                        .IsUnique();

                    b.ToTable("EntiteJurModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.JournalisationModel", b =>
                {
                    b.Property<int>("IdNotif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotif"));

                    b.Property<string>("Cheminfichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContenuNotif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateArchive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateNotif")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dossier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<string>("ModeNotif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefPret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatutNotif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeAnnexe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeNotif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNotif");

                    b.HasIndex("IdActe");

                    b.ToTable("JournalisationModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.PretModel", b =>
                {
                    b.Property<int>("IdPret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPret"));

                    b.Property<string>("Accessoires")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebutRemboursemnt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDerniereEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePremiereEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSignaturePret")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureMoisPret")
                        .HasColumnType("integer");

                    b.Property<string>("EtatPret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdActe")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantConcours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontantDerniereEcheance")
                        .HasColumnType("numeric");

                    b.Property<string>("MontantLettrePret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantPremiereEcheance")
                        .HasColumnType("numeric");

                    b.Property<string>("ObjetPret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceConvention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Taux")
                        .HasColumnType("numeric");

                    b.HasKey("IdPret");

                    b.HasIndex("IdActe")
                        .IsUnique();

                    b.ToTable("PretModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.RolesClientActModel", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MentionManuelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRole");

                    b.ToTable("RolesClientActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.TypesActModel", b =>
                {
                    b.Property<int>("IdActe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActe"));

                    b.Property<DateTime?>("DateArchivage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEnvoiValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateGenerationPdf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateRejet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUploadSignature")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FichierValidationPath")
                        .HasColumnType("text");

                    b.Property<int>("IdAjout")
                        .HasColumnType("integer");

                    b.Property<int?>("IdBnq")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("JsonSnapshotPath")
                        .HasColumnType("text");

                    b.Property<string>("MotifRejet")
                        .HasColumnType("text");

                    b.Property<string>("NomTypesActe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PdfGenerePath")
                        .HasColumnType("text");

                    b.Property<string>("PdfSignePath")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatutWorkflow")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidateurId")
                        .HasColumnType("integer");

                    b.HasKey("IdActe");

                    b.HasIndex("IdActe");

                    b.HasIndex("IdAjout");

                    b.HasIndex("IdBnq");

                    b.HasIndex("IdUser");

                    b.ToTable("TypesActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Fonction")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakId")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NomComplet")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GesCPSI_Project.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GesCPSI_Project.Models.AuditLogModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "Acte")
                        .WithMany()
                        .HasForeignKey("IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GesCPSI_Project.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("IdUser");

                    b.Navigation("Acte");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.AutorisationModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithOne("AutorisationModel")
                        .HasForeignKey("GesCPSI_Project.Models.AutorisationModel", "IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.CautionnementModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithOne("CautionnementModel")
                        .HasForeignKey("GesCPSI_Project.Models.CautionnementModel", "IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ChargeModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithOne("ChargeModel")
                        .HasForeignKey("GesCPSI_Project.Models.ChargeModel", "IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ClientActModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithMany("ClientActModels")
                        .HasForeignKey("IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GesCPSI_Project.Models.ClientModel", "ClientModel")
                        .WithMany("ClientActModels")
                        .HasForeignKey("IdClt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GesCPSI_Project.Models.RolesClientActModel", "RolesClientActModel")
                        .WithMany("ClientActModels")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientModel");

                    b.Navigation("RolesClientActModel");

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.EntiteJurModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithOne("EntiteJurModel")
                        .HasForeignKey("GesCPSI_Project.Models.EntiteJurModel", "IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.JournalisationModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithMany("JournalisationModels")
                        .HasForeignKey("IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.PretModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.TypesActModel", "TypesActModel")
                        .WithOne("PretModel")
                        .HasForeignKey("GesCPSI_Project.Models.PretModel", "IdActe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypesActModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.TypesActModel", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.AjoutActModel", "AjoutActModel")
                        .WithMany("TypesActModels")
                        .HasForeignKey("IdAjout")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GesCPSI_Project.Models.BanqueModel", "BanqueModel")
                        .WithMany("TypesActModels")
                        .HasForeignKey("IdBnq")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GesCPSI_Project.Models.UserModel", "UserModel")
                        .WithMany("ActesSaisis")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AjoutActModel");

                    b.Navigation("BanqueModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GesCPSI_Project.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GesCPSI_Project.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GesCPSI_Project.Models.AjoutActModel", b =>
                {
                    b.Navigation("TypesActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.BanqueModel", b =>
                {
                    b.Navigation("TypesActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.ClientModel", b =>
                {
                    b.Navigation("ClientActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.RolesClientActModel", b =>
                {
                    b.Navigation("ClientActModels");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.TypesActModel", b =>
                {
                    b.Navigation("AutorisationModel");

                    b.Navigation("CautionnementModel");

                    b.Navigation("ChargeModel");

                    b.Navigation("ClientActModels");

                    b.Navigation("EntiteJurModel");

                    b.Navigation("JournalisationModels");

                    b.Navigation("PretModel");
                });

            modelBuilder.Entity("GesCPSI_Project.Models.UserModel", b =>
                {
                    b.Navigation("ActesSaisis");
                });
#pragma warning restore 612, 618
        }
    }
}
